INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇫","Afghanistan","93");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇱","Albania","345");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇩🇿","Algeria","213");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇩","Andorra","376");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇴","Angola","244");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇬","Antigua and Barbuda","1-268");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇷","Argentina","54");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇲","Armenia","374");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇺","Australia","61");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇹","Austria","43");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇿","Azerbaijan","994");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇸","Bahamas","1-242");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇭","Bahrain","973");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇩","Bangladesh","880");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇧","Barbados","1-246");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇾","Belarus","375");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇪","Belgium","32");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇿","Belize","501");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇯","Benin","229");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇹","Bhutan","975");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇴","Bolivia","591");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇦","Bosnia and Herzegovina","387");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇼","Botswana","267");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇷","Brazil","45");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇳","Brunei","673");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇬","Bulgaria","359");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇫","Burkina Faso","226");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇧🇮","Burundi","257");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇻","Cabo Verde","238");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇭","Cambodia","845");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇲","Cameroon","237");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇦","Canada","1");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇾","Cayman Islands","1");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇫","Central African Republic","236");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇩","Chad","235");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇱","Chile","46");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇳","China","86");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇴","Colombia","57");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇲","Comoros","269");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇰","Cook Islands","682");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇷","Costa Rica","506");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇭🇷","Croatia","385");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇺","Cuba","53");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇾","Cyprus","357");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇿","Czechia","420");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇩","Democratic Republic of Congo","243");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇩🇰","Denmark","45");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇩🇯","Djibouti","253");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇩🇲","Dominica","1-767");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇩🇴","Dominican Republic","1");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇪🇨","Ecuador","593");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇪🇬","Egypt","20");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇻","El Salvador","503");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇶","Equatorial Guinea","240");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇪🇷","Eritrea","291");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇪🇪","Estonia","372");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇿","Eswatini","268");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇪🇹","Ethiopia","251");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇫🇯","Fiji","679");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇫🇮","Finland","358");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇫🇷","France","33");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇦","Gabon","241");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇲","Gambia","220");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇪","Georgia","995");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇩🇪","Germany","49");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇭","Ghana","233");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇷","Greece","30");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇩","Grenada","1-473");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇹","Guatemala","502");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇳","Guinea","224");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇼","Guinea-Bissau","245");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇾","Guyana","592");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇭🇹","Haiti","509");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇭🇳","Honduras","504");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇭🇺","Hungary","36");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇸","Iceland","354");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇳","India","91");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇩","Indonesia","62");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇷","Iran","98");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇶","Iraq","964");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇪","Ireland","353");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇱","Israel","972");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇮🇹","Italy","39");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇮","Ivory Coast(Côte d’Ivoire)","225");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇯🇲","Jamaica","1-876");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇯🇵","Japan","81");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇯🇴","Jordan","962");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇿","Kazakhstan","7");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇪","Kenya","254");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇮","Kiribati","686");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇽🇰","Kosovo","383");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇼","Kuwait","965");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇬","Kyrgyzstan","996");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇦","Laos","846");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇻","Latvia","371");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇧","Lebanon","961");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇸","Lesotho","266");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇷","Liberia","231");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇾","Libya","218");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇮","Liechtenstein","423");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇹","Lithuania","370");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇺","Luxembourg","352");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇬","Madagascar","261");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇼","Malawi","265");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇾","Malaysia","60");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇻","Maldives","960");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇱","Mali","223");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇹","Malta","346");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇭","Marshall Islands","692");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇷","Mauritania","222");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇺","Mauritius","230");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇽","Mexico","52");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇫🇲","Micronesia","691");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇩","Moldova","373");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇨","Monaco","377");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇳","Mongolia","976");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇪","Montenegro","382");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇦","Morocco","212");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇿","Mozambique","258");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇲","Myanmar","95");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇦","Namibia","264");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇷","Nauru","674");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇵","Nepal","977");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇱","Netherlands","31");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇿","New Zealand","64");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇮","Nicaragua","505");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇪","Niger","227");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇬","Nigeria","234");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇺","Niue","683");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇵","North Korea","850");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇲🇰","North Macedonia","389");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇳🇴","Norway","47");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇴🇲","Oman","968");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇰","Pakistan","92");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇼","Palau","680");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇸","Palestine","970");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇦","Panama","507");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇬","Papua New Guinea","675");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇾","Paraguay","595");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇪","Peru","51");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇭","Philippines","63");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇱","Poland","48");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇵🇹","Portugal","351");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇶🇦","Qatar","974");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇬","Republic of Congo","242");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇷🇴","Romania","40");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇷🇺","Russia","7");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇷🇼","Rwanda","250");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇳","Saint Kitts and Nevis","1-869");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇨","Saint Lucia","1-758");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇻🇨","Saint Vincent and Grenadines","1-784");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇼🇸","Samoa","685");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇲","San Marino","378");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇹","São Tomé and Príncipe","239");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇦","Saudi Arabia","966");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇳","Senegal","221");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇷🇸","Serbia","381");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇨","Seychelles","248");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇱","Sierra Leone","232");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇬","Singapore","65");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇰","Slovakia","421");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇮","Slovenia","386");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇧","Solomon Islands","677");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇴","Somalia","252");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇿🇦","South Africa","27");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇰🇷","South Korea","82");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇸","South Sudan","211");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇪🇸","Spain","34");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇱🇰","Sri Lanka","94");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇩","Sudan","249");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇷","Suriname","597");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇪","Sweden","46");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇨🇭","Switzerland","41");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇸🇾","Syria","963");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇼","Taiwan","886");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇯","Tajikistan","992");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇿","Tanzania","245");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇭","Thailand","66");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇱","Timor-Leste","670");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇬","Togo","228");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇴","Tonga","676");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇹","Trinidad and Tobago","1-868");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇳","Tunisia","216");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇷","Turkey(Türkiye)","90");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇲","Turkmenistan","993");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇹🇻","Tuvalu","688");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇺🇬","Uganda","246");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇺🇦","Ukraine","380");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇦🇪","United Arab Emirates","971");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇬🇧","United Kingdom","44");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇺🇸","United States","1");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇺🇾","Uruguay","598");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇺🇿","Uzbekistan","998");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇻🇺","Vanuatu","678");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇻🇦","Vatican(Holy See)","379");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇻🇪","Venezuela","58");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇻🇳","Vietnam","84");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇾🇪","Yemen","967");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇿🇲","Zambia","260");
INSERT INTO countries(country_flag,country_name,country_code) VALUES ("🇿🇼","Zimbabwe","263");
